/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTransactionsRouteImport } from './routes/_auth.transactions'
import { Route as AuthTrans_vaRouteImport } from './routes/_auth.trans_va'
import { Route as AuthSupportRouteImport } from './routes/_auth.support'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthSale_channelRouteImport } from './routes/_auth.sale_channel'
import { Route as AuthReceiptRouteImport } from './routes/_auth.receipt'
import { Route as AuthQrpayRouteImport } from './routes/_auth.qrpay'
import { Route as AuthInvoicesRouteImport } from './routes/_auth.invoices'
import { Route as AuthIntegrationRouteImport } from './routes/_auth.integration'
import { Route as AuthHomeRouteImport } from './routes/_auth.home'
import { Route as AuthBudgetRouteImport } from './routes/_auth.budget'
import { Route as AuthBillingRouteImport } from './routes/_auth.billing'
import { Route as AuthAccountRouteImport } from './routes/_auth.account'
import { Route as AuthSplatRouteImport } from './routes/_auth.$'
import { Route as AuthInvoicesIndexRouteImport } from './routes/_auth.invoices.index'
import { Route as AuthTransactionsTxnRouteImport } from './routes/_auth.transactions.$txn'
import { Route as AuthQrpayResultRouteImport } from './routes/_auth.qrpay.result'
import { Route as AuthQrpayProcessRouteImport } from './routes/_auth.qrpay.process'
import { Route as AuthMTransactionsRouteImport } from './routes/_auth.m.transactions'
import { Route as AuthMSettingsRouteImport } from './routes/_auth.m.settings'
import { Route as AuthMHomeRouteImport } from './routes/_auth.m.home'
import { Route as AuthMDeviceRouteImport } from './routes/_auth.m.device'
import { Route as AuthMAccountRouteImport } from './routes/_auth.m.account'
import { Route as AuthMSplatRouteImport } from './routes/_auth.m.$'
import { Route as AuthInvoicesInvoiceIdRouteImport } from './routes/_auth.invoices.$invoiceId'
import { Route as AuthMTransactionsTxnRouteImport } from './routes/_auth.m.transactions.$txn'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTransactionsRoute = AuthTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrans_vaRoute = AuthTrans_vaRouteImport.update({
  id: '/trans_va',
  path: '/trans_va',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSupportRoute = AuthSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSale_channelRoute = AuthSale_channelRouteImport.update({
  id: '/sale_channel',
  path: '/sale_channel',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReceiptRoute = AuthReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQrpayRoute = AuthQrpayRouteImport.update({
  id: '/qrpay',
  path: '/qrpay',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesRoute = AuthInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIntegrationRoute = AuthIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBudgetRoute = AuthBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingRoute = AuthBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesIndexRoute = AuthInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthInvoicesRoute,
} as any)
const AuthTransactionsTxnRoute = AuthTransactionsTxnRouteImport.update({
  id: '/$txn',
  path: '/$txn',
  getParentRoute: () => AuthTransactionsRoute,
} as any)
const AuthQrpayResultRoute = AuthQrpayResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AuthQrpayRoute,
} as any)
const AuthQrpayProcessRoute = AuthQrpayProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AuthQrpayRoute,
} as any)
const AuthMTransactionsRoute = AuthMTransactionsRouteImport.update({
  id: '/m/transactions',
  path: '/m/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMSettingsRoute = AuthMSettingsRouteImport.update({
  id: '/m/settings',
  path: '/m/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMHomeRoute = AuthMHomeRouteImport.update({
  id: '/m/home',
  path: '/m/home',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMDeviceRoute = AuthMDeviceRouteImport.update({
  id: '/m/device',
  path: '/m/device',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMAccountRoute = AuthMAccountRouteImport.update({
  id: '/m/account',
  path: '/m/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMSplatRoute = AuthMSplatRouteImport.update({
  id: '/m/$',
  path: '/m/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesInvoiceIdRoute = AuthInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AuthInvoicesRoute,
} as any)
const AuthMTransactionsTxnRoute = AuthMTransactionsTxnRouteImport.update({
  id: '/$txn',
  path: '/$txn',
  getParentRoute: () => AuthMTransactionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthSplatRoute
  '/account': typeof AuthAccountRoute
  '/billing': typeof AuthBillingRoute
  '/budget': typeof AuthBudgetRoute
  '/home': typeof AuthHomeRoute
  '/integration': typeof AuthIntegrationRoute
  '/invoices': typeof AuthInvoicesRouteWithChildren
  '/qrpay': typeof AuthQrpayRouteWithChildren
  '/receipt': typeof AuthReceiptRoute
  '/sale_channel': typeof AuthSale_channelRoute
  '/settings': typeof AuthSettingsRoute
  '/support': typeof AuthSupportRoute
  '/trans_va': typeof AuthTrans_vaRoute
  '/transactions': typeof AuthTransactionsRouteWithChildren
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/m/$': typeof AuthMSplatRoute
  '/m/account': typeof AuthMAccountRoute
  '/m/device': typeof AuthMDeviceRoute
  '/m/home': typeof AuthMHomeRoute
  '/m/settings': typeof AuthMSettingsRoute
  '/m/transactions': typeof AuthMTransactionsRouteWithChildren
  '/qrpay/process': typeof AuthQrpayProcessRoute
  '/qrpay/result': typeof AuthQrpayResultRoute
  '/transactions/$txn': typeof AuthTransactionsTxnRoute
  '/invoices/': typeof AuthInvoicesIndexRoute
  '/m/transactions/$txn': typeof AuthMTransactionsTxnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthSplatRoute
  '/account': typeof AuthAccountRoute
  '/billing': typeof AuthBillingRoute
  '/budget': typeof AuthBudgetRoute
  '/home': typeof AuthHomeRoute
  '/integration': typeof AuthIntegrationRoute
  '/qrpay': typeof AuthQrpayRouteWithChildren
  '/receipt': typeof AuthReceiptRoute
  '/sale_channel': typeof AuthSale_channelRoute
  '/settings': typeof AuthSettingsRoute
  '/support': typeof AuthSupportRoute
  '/trans_va': typeof AuthTrans_vaRoute
  '/transactions': typeof AuthTransactionsRouteWithChildren
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/m/$': typeof AuthMSplatRoute
  '/m/account': typeof AuthMAccountRoute
  '/m/device': typeof AuthMDeviceRoute
  '/m/home': typeof AuthMHomeRoute
  '/m/settings': typeof AuthMSettingsRoute
  '/m/transactions': typeof AuthMTransactionsRouteWithChildren
  '/qrpay/process': typeof AuthQrpayProcessRoute
  '/qrpay/result': typeof AuthQrpayResultRoute
  '/transactions/$txn': typeof AuthTransactionsTxnRoute
  '/invoices': typeof AuthInvoicesIndexRoute
  '/m/transactions/$txn': typeof AuthMTransactionsTxnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/$': typeof AuthSplatRoute
  '/_auth/account': typeof AuthAccountRoute
  '/_auth/billing': typeof AuthBillingRoute
  '/_auth/budget': typeof AuthBudgetRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/integration': typeof AuthIntegrationRoute
  '/_auth/invoices': typeof AuthInvoicesRouteWithChildren
  '/_auth/qrpay': typeof AuthQrpayRouteWithChildren
  '/_auth/receipt': typeof AuthReceiptRoute
  '/_auth/sale_channel': typeof AuthSale_channelRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/support': typeof AuthSupportRoute
  '/_auth/trans_va': typeof AuthTrans_vaRoute
  '/_auth/transactions': typeof AuthTransactionsRouteWithChildren
  '/_auth/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/_auth/m/$': typeof AuthMSplatRoute
  '/_auth/m/account': typeof AuthMAccountRoute
  '/_auth/m/device': typeof AuthMDeviceRoute
  '/_auth/m/home': typeof AuthMHomeRoute
  '/_auth/m/settings': typeof AuthMSettingsRoute
  '/_auth/m/transactions': typeof AuthMTransactionsRouteWithChildren
  '/_auth/qrpay/process': typeof AuthQrpayProcessRoute
  '/_auth/qrpay/result': typeof AuthQrpayResultRoute
  '/_auth/transactions/$txn': typeof AuthTransactionsTxnRoute
  '/_auth/invoices/': typeof AuthInvoicesIndexRoute
  '/_auth/m/transactions/$txn': typeof AuthMTransactionsTxnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/account'
    | '/billing'
    | '/budget'
    | '/home'
    | '/integration'
    | '/invoices'
    | '/qrpay'
    | '/receipt'
    | '/sale_channel'
    | '/settings'
    | '/support'
    | '/trans_va'
    | '/transactions'
    | '/invoices/$invoiceId'
    | '/m/$'
    | '/m/account'
    | '/m/device'
    | '/m/home'
    | '/m/settings'
    | '/m/transactions'
    | '/qrpay/process'
    | '/qrpay/result'
    | '/transactions/$txn'
    | '/invoices/'
    | '/m/transactions/$txn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$'
    | '/account'
    | '/billing'
    | '/budget'
    | '/home'
    | '/integration'
    | '/qrpay'
    | '/receipt'
    | '/sale_channel'
    | '/settings'
    | '/support'
    | '/trans_va'
    | '/transactions'
    | '/invoices/$invoiceId'
    | '/m/$'
    | '/m/account'
    | '/m/device'
    | '/m/home'
    | '/m/settings'
    | '/m/transactions'
    | '/qrpay/process'
    | '/qrpay/result'
    | '/transactions/$txn'
    | '/invoices'
    | '/m/transactions/$txn'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/$'
    | '/_auth/account'
    | '/_auth/billing'
    | '/_auth/budget'
    | '/_auth/home'
    | '/_auth/integration'
    | '/_auth/invoices'
    | '/_auth/qrpay'
    | '/_auth/receipt'
    | '/_auth/sale_channel'
    | '/_auth/settings'
    | '/_auth/support'
    | '/_auth/trans_va'
    | '/_auth/transactions'
    | '/_auth/invoices/$invoiceId'
    | '/_auth/m/$'
    | '/_auth/m/account'
    | '/_auth/m/device'
    | '/_auth/m/home'
    | '/_auth/m/settings'
    | '/_auth/m/transactions'
    | '/_auth/qrpay/process'
    | '/_auth/qrpay/result'
    | '/_auth/transactions/$txn'
    | '/_auth/invoices/'
    | '/_auth/m/transactions/$txn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trans_va': {
      id: '/_auth/trans_va'
      path: '/trans_va'
      fullPath: '/trans_va'
      preLoaderRoute: typeof AuthTrans_vaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/support': {
      id: '/_auth/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthSupportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sale_channel': {
      id: '/_auth/sale_channel'
      path: '/sale_channel'
      fullPath: '/sale_channel'
      preLoaderRoute: typeof AuthSale_channelRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/receipt': {
      id: '/_auth/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof AuthReceiptRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/qrpay': {
      id: '/_auth/qrpay'
      path: '/qrpay'
      fullPath: '/qrpay'
      preLoaderRoute: typeof AuthQrpayRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integration': {
      id: '/_auth/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AuthIntegrationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/budget': {
      id: '/_auth/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthBudgetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing': {
      id: '/_auth/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/$': {
      id: '/_auth/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices/': {
      id: '/_auth/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthInvoicesIndexRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
    '/_auth/transactions/$txn': {
      id: '/_auth/transactions/$txn'
      path: '/$txn'
      fullPath: '/transactions/$txn'
      preLoaderRoute: typeof AuthTransactionsTxnRouteImport
      parentRoute: typeof AuthTransactionsRoute
    }
    '/_auth/qrpay/result': {
      id: '/_auth/qrpay/result'
      path: '/result'
      fullPath: '/qrpay/result'
      preLoaderRoute: typeof AuthQrpayResultRouteImport
      parentRoute: typeof AuthQrpayRoute
    }
    '/_auth/qrpay/process': {
      id: '/_auth/qrpay/process'
      path: '/process'
      fullPath: '/qrpay/process'
      preLoaderRoute: typeof AuthQrpayProcessRouteImport
      parentRoute: typeof AuthQrpayRoute
    }
    '/_auth/m/transactions': {
      id: '/_auth/m/transactions'
      path: '/m/transactions'
      fullPath: '/m/transactions'
      preLoaderRoute: typeof AuthMTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/m/settings': {
      id: '/_auth/m/settings'
      path: '/m/settings'
      fullPath: '/m/settings'
      preLoaderRoute: typeof AuthMSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/m/home': {
      id: '/_auth/m/home'
      path: '/m/home'
      fullPath: '/m/home'
      preLoaderRoute: typeof AuthMHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/m/device': {
      id: '/_auth/m/device'
      path: '/m/device'
      fullPath: '/m/device'
      preLoaderRoute: typeof AuthMDeviceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/m/account': {
      id: '/_auth/m/account'
      path: '/m/account'
      fullPath: '/m/account'
      preLoaderRoute: typeof AuthMAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/m/$': {
      id: '/_auth/m/$'
      path: '/m/$'
      fullPath: '/m/$'
      preLoaderRoute: typeof AuthMSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices/$invoiceId': {
      id: '/_auth/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
    '/_auth/m/transactions/$txn': {
      id: '/_auth/m/transactions/$txn'
      path: '/$txn'
      fullPath: '/m/transactions/$txn'
      preLoaderRoute: typeof AuthMTransactionsTxnRouteImport
      parentRoute: typeof AuthMTransactionsRoute
    }
  }
}

interface AuthInvoicesRouteChildren {
  AuthInvoicesInvoiceIdRoute: typeof AuthInvoicesInvoiceIdRoute
  AuthInvoicesIndexRoute: typeof AuthInvoicesIndexRoute
}

const AuthInvoicesRouteChildren: AuthInvoicesRouteChildren = {
  AuthInvoicesInvoiceIdRoute: AuthInvoicesInvoiceIdRoute,
  AuthInvoicesIndexRoute: AuthInvoicesIndexRoute,
}

const AuthInvoicesRouteWithChildren = AuthInvoicesRoute._addFileChildren(
  AuthInvoicesRouteChildren,
)

interface AuthQrpayRouteChildren {
  AuthQrpayProcessRoute: typeof AuthQrpayProcessRoute
  AuthQrpayResultRoute: typeof AuthQrpayResultRoute
}

const AuthQrpayRouteChildren: AuthQrpayRouteChildren = {
  AuthQrpayProcessRoute: AuthQrpayProcessRoute,
  AuthQrpayResultRoute: AuthQrpayResultRoute,
}

const AuthQrpayRouteWithChildren = AuthQrpayRoute._addFileChildren(
  AuthQrpayRouteChildren,
)

interface AuthTransactionsRouteChildren {
  AuthTransactionsTxnRoute: typeof AuthTransactionsTxnRoute
}

const AuthTransactionsRouteChildren: AuthTransactionsRouteChildren = {
  AuthTransactionsTxnRoute: AuthTransactionsTxnRoute,
}

const AuthTransactionsRouteWithChildren =
  AuthTransactionsRoute._addFileChildren(AuthTransactionsRouteChildren)

interface AuthMTransactionsRouteChildren {
  AuthMTransactionsTxnRoute: typeof AuthMTransactionsTxnRoute
}

const AuthMTransactionsRouteChildren: AuthMTransactionsRouteChildren = {
  AuthMTransactionsTxnRoute: AuthMTransactionsTxnRoute,
}

const AuthMTransactionsRouteWithChildren =
  AuthMTransactionsRoute._addFileChildren(AuthMTransactionsRouteChildren)

interface AuthRouteChildren {
  AuthSplatRoute: typeof AuthSplatRoute
  AuthAccountRoute: typeof AuthAccountRoute
  AuthBillingRoute: typeof AuthBillingRoute
  AuthBudgetRoute: typeof AuthBudgetRoute
  AuthHomeRoute: typeof AuthHomeRoute
  AuthIntegrationRoute: typeof AuthIntegrationRoute
  AuthInvoicesRoute: typeof AuthInvoicesRouteWithChildren
  AuthQrpayRoute: typeof AuthQrpayRouteWithChildren
  AuthReceiptRoute: typeof AuthReceiptRoute
  AuthSale_channelRoute: typeof AuthSale_channelRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSupportRoute: typeof AuthSupportRoute
  AuthTrans_vaRoute: typeof AuthTrans_vaRoute
  AuthTransactionsRoute: typeof AuthTransactionsRouteWithChildren
  AuthMSplatRoute: typeof AuthMSplatRoute
  AuthMAccountRoute: typeof AuthMAccountRoute
  AuthMDeviceRoute: typeof AuthMDeviceRoute
  AuthMHomeRoute: typeof AuthMHomeRoute
  AuthMSettingsRoute: typeof AuthMSettingsRoute
  AuthMTransactionsRoute: typeof AuthMTransactionsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSplatRoute: AuthSplatRoute,
  AuthAccountRoute: AuthAccountRoute,
  AuthBillingRoute: AuthBillingRoute,
  AuthBudgetRoute: AuthBudgetRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthIntegrationRoute: AuthIntegrationRoute,
  AuthInvoicesRoute: AuthInvoicesRouteWithChildren,
  AuthQrpayRoute: AuthQrpayRouteWithChildren,
  AuthReceiptRoute: AuthReceiptRoute,
  AuthSale_channelRoute: AuthSale_channelRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSupportRoute: AuthSupportRoute,
  AuthTrans_vaRoute: AuthTrans_vaRoute,
  AuthTransactionsRoute: AuthTransactionsRouteWithChildren,
  AuthMSplatRoute: AuthMSplatRoute,
  AuthMAccountRoute: AuthMAccountRoute,
  AuthMDeviceRoute: AuthMDeviceRoute,
  AuthMHomeRoute: AuthMHomeRoute,
  AuthMSettingsRoute: AuthMSettingsRoute,
  AuthMTransactionsRoute: AuthMTransactionsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
